/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BooksSetListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheBooksSetList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheBooksSetList.onFilterBar().iCheckFilterField("title");
            Then.onTheBooksSetList.onFilterBar().iCheckFilterField("author");
            Then.onTheBooksSetList.onFilterBar().iCheckFilterField("price");
            Then.onTheBooksSetList.onFilterBar().iCheckFilterField("gender");
            Then.onTheBooksSetList.onFilterBar().iCheckFilterField("ageGroup");
            Then.onTheBooksSetList.onFilterBar().iCheckFilterField("publishedDate");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheBooksSetList.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheBooksSetList.onFilterBar().iExecuteSearch();
        //     Then.onTheBooksSetList.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheBooksSetList.onTable().iCheckColumns(undefined, {"title":{"header":"Title"},"author":{"header":"Author"},"price":{"header":"Price"},"publishedDate":{"header":" Publication Date"},"gender":{"header":"Gender"},"ageGroup":{"header":"Age Group"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheBooksSetList.onFilterBar().iExecuteSearch();
            
            Then.onTheBooksSetList.onTable().iCheckRows();

            When.onTheBooksSetList.onTable().iPressRow(0);
            Then.onTheBooksSetObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});