/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BooksSetObjectPageObjectPage journey");

        opaTest("Navigate to BooksSetObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheBooksSetList.onFilterBar().iExecuteSearch();

            Then.onTheBooksSetList.onTable().iCheckRows();
            When.onTheBooksSetList.onTable().iPressRow(0);

            Then.onTheBooksSetObjectPage.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheBooksSetObjectPage.iCheckNumberOfSections(3);
            When.onTheBooksSetObjectPage.iPressSectionIconTabFilterButton("FieldGroup::General");
            Then.onTheBooksSetObjectPage.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheBooksSetObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "title" });
            Then.onTheBooksSetObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "author" });
            Then.onTheBooksSetObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "gender" });
            Then.onTheBooksSetObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "ageGroup" });
            When.onTheBooksSetObjectPage.iPressSectionIconTabFilterButton("FieldGroup::Publication");
            Then.onTheBooksSetObjectPage.iCheckSection({ section: "FieldGroup::Publication" });
            Then.onTheBooksSetObjectPage.onForm({ section: "FieldGroup::Publication" }).iCheckField({ property: "publishedDate" });
            When.onTheBooksSetObjectPage.iPressSectionIconTabFilterButton("FieldGroup::Pricing");
            Then.onTheBooksSetObjectPage.iCheckSection({ section: "FieldGroup::Pricing" });
            Then.onTheBooksSetObjectPage.onForm({ section: "FieldGroup::Pricing" }).iCheckField({ property: "price" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});